"$schema" = "schemas/schema.json"
[default]
description = """
# Tauri `serialport` default permissions

This configuration file defines the default permissions granted
to the serialport.

### Granted Permissions

This default permission set enables all read-related commands and
allows access to the `$APP` folder and sub directories created in it.
The location of the `$APP` folder depends on the operating system,
where the application is run.

In general the `$APP` folder needs to be manually created
by the application at runtime, before accessing files or folders
in it is possible.

### Denied Permissions

This default permission set prevents access to critical components
of the Tauri application by default.
On Windows the webview data folder access is denied.

"""
permissions = [
    "allow-managed-ports",
    "allow-available-ports",
    "allow-available-ports-direct",
    "allow-cancel-read",
    "allow-close",
    "allow-close-all",
    "allow-force-close",
    "allow-open",
    "allow-read",
    "allow-write",
    "allow-write-binary",
    "allow-start-listening",
    "allow-stop-listening",
    "allow-available-ports",
    "allow-available-ports-direct",
    "allow-bytes-to-read",
    "allow-bytes-to-write",
    "allow-cancel-read",
    "allow-clear-break",
    "allow-clear-buffer",
    "allow-close",
    "allow-close-all",
    "allow-force-close",
    "allow-managed-ports",
    "allow-open",
    "allow-read",
    "allow-read-binary",
    "allow-read-carrier-detect",
    "allow-read-cd",
    "allow-read-clear-to-send",
    "allow-read-cts",
    "allow-read-data-set-ready",
    "allow-read-dsr",
    "allow-read-dtr",
    "allow-read-ri",
    "allow-read-ring-indicator",
    "allow-set-baud-rate",
    "allow-set-break",
    "allow-set-data-bits",
    "allow-set-flow-control",
    "allow-set-parity",
    "allow-set-stop-bits",
    "allow-set-timeout",
    "allow-start-listening",
    "allow-stop-listening",
    "allow-write",
    "allow-write-binary",
    "allow-write-data-terminal-ready",
    "allow-write-dtr",
    "allow-write-request-to-send",
    "allow-write-rts"
]
